spring:
  datasource:
    #   数据源基本配置
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/engineproject
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml